---
title: "Course materials"
---

In this page you can find the course materials, specifically the slide decks I will be using during the lectures.

## Slides

1. [Introduction, Motivation](slides/01_intro_motivation.qmd)  
2. [Game Theory Strategic Form](slides/02_game_theory_strategic_form.qmd)  
3. [Game Theory Extensive Form](slides/03_game_theory_extensive_form.qmd)  
4. [Games with Asymmetric Information](slides/04_games_with_assymetric_info.qmd)
5. [Applications](slides/05_applications.qmd)

## Some Extra Material

1. [Wealth and the Principal-Agent Matching, Paulo Fagandini, 2022](https://pfagandini.github.io/preprints/P_A_Matching_Accepted.pdf)
2. [Computing Profit-Maximizing Bid Shading Factors in First-Price Sealed-Bid Auctions, Paulo Fagandini and Ingemar Dierickx, 2023](https://pfagandini.github.io/preprints/Bidding_Accepted.pdf)
3. [Rules, Discretion and Reputation in a model of Monetary Policy, Robert Barro and David Gordon, 1983](https://www.nber.org/system/files/working_papers/w1079/w1079.pdf)
4. [Dynamic Inconsistency, Cooperation and the Benevolent Dissembling Government, Stanley Fisher, 1980](https://people.bu.edu/rking/SZG2011WK3/DAY2/fischer-jedc1980.pdf)

## Problem Set

1. [Problem Set](problem_set/Problem_Set.pdf)