---
title: "Fundamentals of <br> Game Theory"
author: "Paulo Fagandini"
institute: "Prague University of Economics and Business <br> Faculty of Informatics and Statistics"
format: 
  revealjs:
    self-contained: false
    logo: ../images/vse.jpg
    slide-number: true
    cross-ref: true
    incremental: true
    math: 
      method: mathjax
    transition: slide
    footer: "Economics of Incentives"
    from: markdown+emoji
    code-overflow: wrap
    code-block-font-size: 0.75em
    progress: true
editor: source

---

<div style="font-size: 70%;">
</div>

# Introduction

## Core Bibliography

The core of the contents of this chapter takes as reference the book

:book: *Strategies and Games: Theory and Practice* by Prajit K. Dutta. 2001 MIT Press.

# Strategic Form Games

## Strategic Form Games

We will focus the utilization of Strategic Form games to model simoultaneous games, and therefore the *timing* of the game becomes unnecessary. We will just need the set of players, their strategies, and the payoffs associated to any strategy profile.

## Strategic Form Games 

1. Let's name our players $P1$ and $P2$
2. Let $S_i$ be the set of strategies available for player $i$
3. Say $\pi_i(s_1,s_2)$ be the payoff for player $i$, with $s_1\in S_1$ and $s_2\in S2$.

## Strategic Form Games 

Suppose $S_1=\{U,D\}$ and $S_2=\{L,R\}$, the payoff matrix would be:

| 1$\setminus$ 2 | $L$ | $R$ |
| --: | :-: | :-: |
| $U$ | $(\pi_1(U,L),\pi_2(U,L))$ | $(\pi_1(U,R),\pi_2(U,R))$ |
| $D$ | $(\pi_1(D,L),\pi_2(D,L))$ | $(\pi_1(D,R),\pi_2(D,R))$ |

. . .

:::{.callout-important}

The payoff for each player, depends on the strategy profile, that in each position on the table, is the same.

:::

## Strategic Form Games

What if we have more than 2 players, and strategies?

. . .

1. If we have $N\in\mathbb{N}$ players, we will index them: 1,2, $\dots$, $N$.
2. Their strategy space is $S_i$.
3. A strategy profile is an ordered tuple $(s_1,s_2,\dots,s_N)\in S_1\times S_2\times\dots S_N$.
4. $\pi_i(s_1,\dots,s_N)$ represents the payoff for player $i$, given the strategy profile $(s_1,s_2,\dots,s_N)$.

. . .

We can do better

## Strategic Form Games

Given that the strategies of the other players (other than player $i$) are out player's $i$ control, we will summarize them as $s_{-i}$. So we will write:

$$\pi_i(s_1,\dots,s_N) = \pi_i(s_i,s_{-i}) $$

And $s_{-i}$ represents all chosen $s_j$ when $j\neq i$. We could say *the other's* strategies in the current strategy profile.

## The Prissoner's Dilemma

This is a classical game, and this is a great opportunity to introduce it:

<div style="font-size: 70%;">

Two prissoners, Calvin and Klein, are hauled in for a suspected crime. The $DA$ speaks to each prisoner separately, and tells them that she more or less has the evidence to convict them but they could make her work a little easier (and help themselves) if they confess to the crime. She offers each of them the following deal: "*Confess* to the crime, turn a witness for the State, and implicate the ohter guy, and you will do no time. Of course, your confession will be worth a lot less if the other guy confesses as well. I that case, you both go in for 5 years. If you *do not confess*, however, be aware that we will nail you with the other guy's confession, and then you will do fifteen years. In the event that I cannot get a confession from either of you, I have enough evidence to put you both away for a year."

</div>

<div style="font-size: 40%;">

Prajit K. Dutta's version of this game, in the book *Strategies and Games: Theory and Practice*. MIT Press, 2001.

</div>

## The Prissoner's Dilemma

Note that this would be something like a *reverse payoff* matrix, as as a payoff we are writing down the years in prison, and most likely, the lower the number of years in prison, the better for both prissoners!

| Calvin - Klein | *Confess* | *Not Confess* |
| --- | :--: | :--: |
| *Confess* | $(5,5)$ | $(0,15)$ |
| *Not Confess* | $(15,0)$ | $(1,1)$ |

We can turn this table into something more traditional, assuming that each year in prison, equals a payoff of -1.

## The Prissoner's Dilemma

| Calvin - Klein | *Confess* | *Not Confess* |
| --- | :--: | :--: |
| *Confess* | $(-5,-5)$ | $(0,-15)$ |
| *Not Confess* | $(-15,0)$ | $(-1,-1)$ |

1. Suppose Calvin thinks Klein will *confess*. In that case, Calvin would be much better **confessing**! ($-5 > -15$).
2. Suppose Calvin thinks Klein will *Not Confess*. In that case, Calvin would also be much better off by **confessing**! ($0 > -1$)

## The Prissoner's Dilemma

Symmetrically, these options are the same for Klein. Note that *confess* is a **dominant** strategy, because independently of what the other decides, *confess* always generates at least as much payoff as any alternative. You cannot improve over the payoff you can get with *confess*, no matter what your counterpart is doing.

## Equivalence in the Extensive form

We said, these are simoultaneous games, but we do not need that both prissoner's actually chose simoultaneously. It is enough that when one decide, the other does not know what the first prisoner's chose.

## Equivalence in the Extensive form

Think on the Rock-Paper-Scissors game. As both players can see each others hands, simultaneity is necessary.

Suppose now that we introduce a referee. One player tells secretely to the referee what her choice is (rock, paper, or scissors). Then the referee asks the other player, separately what is her own choice. Finally the referee can reveal if there is a winner or a draw. The game works just fine, even though one player played first.

## Equivalence in the Extensive form

The key was that the player that played last, **did not know what the other player played** when she made her decision, and also that the first player, **knew that they other player was unaware of her move** by the time she made her decision.

## Equivalence in the Extensive form

This is the Strategic or Normal form to represent this game:

| 1-2 | $R$ | $P$ | $S$ |
| --: | :--: | :--: | :--: |
| $R$ | $(0,0)$ | $(-1,1)$ | $(1,-1)$ |
| $P$ | $(1,-1)$ | $(0,0)$ | $(-1,1)$ |
| $S$ | $(-1,1)$ | $(1,-1)$ | $(0,0)$ |

## Equivalence in the Extensive form

```{r, engine='tikz', fig.align='center'}

\usetikzlibrary{calc}

\tikzset{
  solid node/.style={circle,draw,inner sep=1.5,fill=black},
  hollow node/.style={circle,draw,inner sep=1.5}
}

\begin{tikzpicture}[scale=1.5,font=\footnotesize]
  \tikzstyle{level 1}=[level distance=15mm,sibling distance=35mm]
  \tikzstyle{level 2}=[level distance=15mm,sibling distance=10mm]

  \node(0)[solid node,label=above:{$P1$}]{}
    child{
      node(1)[solid node, label=above left:{$P2$}]{}
      child{node[hollow node,label=below:{$(0,0)$}]{} edge from parent node[left]{$R$}}
      child{node[hollow node,label=below:{$(-1,1)$}]{} edge from parent node[right]{$P$}}
      child{node[hollow node,label=below:{$(1,-1)$}]{} edge from parent node[right]{$S$}}
      edge from parent node[left,xshift=-3]{$R$}
    }
    child{
      node(2)[solid node, label=above right:{$P2$}]{}
      child{node[hollow node,label=below:{$(1,-1)$}]{} edge from parent node[left]{$R$}}
      child{node[hollow node,label=below:{$(0,0)$}]{} edge from parent node[right]{$P$}}
      child{node[hollow node,label=below:{$(-1,1)$}]{} edge from parent node[right]{$S$}}
      edge from parent node[right,xshift=3]{$P$}
    }
    child{
      node(3)[solid node, label=above right:{$P2$}]{}
      child{node[hollow node,label=below:{$(-1,1)$}]{} edge from parent node[left]{$R$}}
      child{node[hollow node,label=below:{$(1,-1)$}]{} edge from parent node[right]{$P$}}
      child{node[hollow node,label=below:{$(0,0)$}]{} edge from parent node[right]{$S$}}
      edge from parent node[right,xshift=3]{$S$}
    };

   \draw[dashed,rounded corners=10]($(1) + (-.2,.25)$)rectangle($(3) +(.2,-.25)$);
   \node at ($(1)!.5!(2)$) {$P2$};

\end{tikzpicture}

```

<div style="font-size: 70%;">
The dashed *set* represents an information set. This means that all these nodes carry the same information, or that at this point $P2$ does not know exactly in which node she is, and must play accordingly. This is equivalent to a simoultaneous game.
</div>

## Dominant Strategy Solution

Remember the dominan strategy in the Prissoner's dilemma?

*Confess* was dominant, because no matter what the other player did, *confessing* always yielded the highest payoff.

## Dominant Strategy Solution

:::{.callout-note}
## Strongly Dominant Strategy

A strategy $s_i'$ is said to be **strongly** dominant if $$\pi_i(s_i',s_{-i}) > \pi_i(s_i,s_{-i})\quad \forall s_i\in S_i,\ \forall s_{-i}\in\prod_{j\neq i} S_j$$
:::

## Dominant Strategy Solution

:::{.callout-note}
## Weakly Dominant Strategy

A strategy $s_i'$ is said to be **weakly** dominant if $$\pi_i(s_i',s_{-i})\geq \pi_i(s_i,s_{-i})\quad \forall s_i\in S_i,\ \forall s_{-i}\in\prod_{j\neq i} S_j$$ and $$\exists \hat{s}_{-i}\in\prod_{j\neq i} S_j\ s.t.\ \forall s_i \in S_i\setminus\{s_i'\},\ \pi_i(s_i',\hat{s}_{-i})>\pi_i(s_i,\hat{s}_{-i})$$

:::

## Application: Second Price (Sealed Bid) Auctions

Suppose there is an auction, for which $N$ bidders are competing. Each bidder $i$ assigns a value $v_i$ to the object being sold. The auction works like this:

1. Every bidder submit a bid $b_i$ in a sealed envelope.
2. Once all bids are collected, the auctioneer opens the envelope, and announces the winner.
3. The winner pays the value of the **second highest bid**, and gets the object. All other bidders walk out without the item, but without paying anything.

## Application: Second Price Auctions

Any single bidder faces the following dilemma:

* If I bid too much, I will win for sure, but I might end up overpaying.
* If I bid too little, I will lose the auction and walk home empty handed.

## Application: Second Price Auctions

1. If the bidder gets the item, the payoff is $$\pi_i(b_i,b_{-i})=v_i-\max\{b_j\}_{j\neq i}$$
2. If the bidder loses, the payoff is $$\pi_i(b_i,b_{-j})=0$$
3. The expected payoff is then $$E\left[\pi_i(b_i,b_{-i})\right]=Pr\left(b_i>b_{-i}\right)\left(v_i-\max\{b_j\}_{j\neq i}\right)$$

## Application: Second Price Auctions

The question is then, what is the value of $b_i$ that maximizes the expected payoff? *i.e.* what is $b_i^*$?

1. Suppose we chose $b_i^*>v_i$.
2. Suppose we choose $b_i^*<v_i$.
3. What about then if we choose $b_i^*=v_i$?

. . .

This is the solution proposed by William Vickrey, and these types of auctions are known as Vickrey Auctions.

## Application: Second Price Auctions

These auctions present the bidder with some tradeoffs:

1. Enforces true revelation (bidders reveal their true valuations).
2. It is very simple and transparent.
3. Might, under some reasonable assumptions, generate lower prices than other auction formats.
4. Bidders might skip these auctions if they have reasons to hide their valuations from competitors.

## Application: Second Price Auctions

Why now?

. . .

This auction presents an example of a dominant strategy, we saw that $b_i=v_i$ always provides a higher (or equal) than any other bid, and therefore it is a weakly dominant strategy, whatever the other bidders are doing.


## Dominance Solvability

:::{.callout-note}

## Dominated Strategy
A strategy $s_i^\#\in S_i$ is **dominated** by another strategy $s_i'\in S_i$, if the latter does at least as well as $s_i^\#$ against every strategy of the other players, and against some it does strictly better, such that:

$$\pi_i(s_i',s_{-i})\geq\pi_i(s_i^\#,s_{-i}),\quad \forall s_{-i}\in\prod_{j\neq i}S_j$$ and
$$\exists \hat{s}_{-i}\in\prod_{j\neq i} S_j,\ s.t.\ \pi_i(s_i',\hat{s}_{-i})>\pi_i(s_i^\#,\hat{s}_{-i})$$

:::

If a strategy is not *dominated*, then it is said to be **undominated**.

## Dominance Solvability

:::{.callout-note}
## Corollary

If a strategy is **dominated**, it cannot be optimal.

:::

:::{.callout-warning}
## Undominated vs Dominant strategy

Of course, looking at the definition, a **dominant strategy** is optimal, however, not every game has a dominant strategy for every player!

:::

## Dominance Solvability

How can we solve this problem?

:::{.callout-note}
## Iterated Elimination of Dominated Strategies

A first approach to start looking for a solution, could be to reduce a game by removing dominated strategies, *i.e.* all the strategies for which there is always a better alternative whatever the other players chose to do.

:::

## Iterated Elimination of Dominated Strategies

Consider the following game

| P1 - P2 | Left | Right |
| --: | :--: | :--: |
| Up | (1,1) | (0,1) |
| Middle | (0,2) | (1,0) |
| Down | (0,-1) | (0,0) |


1. For $P1$ there is no dominant strategy, but there is a *dominated* strategy, *Down*.

## Iterated Elimination of Dominated Strategies

Consider the following game

| P1 - P2 | Left | Right |
| --: | :--: | :--: |
| Up | (1,1) | (0,1) |
| Middle | (0,2) | (1,0) |


2. For $P2$ now, *Right* provides payoffs that are lower or equal than *Left*, and therefore it is *dominated*.
   
## Iterated Elimination of Dominated Strategies

Consider the following game

| P1 - P2 | Left |
| --: | :--: |
| Up | (1,1) |
| Middle | (0,2) |


3. For $P1$ now, *Up* is clearly the best choice, and the solution is therefore $(Up,Left)$. In this case it is said to be reached by *iterated elimination of dominated strategies (IEDS)*. The game itself is said to be *dominance solvable*.

# Nash Equilibrium

## Nash Equilibrium

So far we have discussed games in terms of "solutions," but, what does that mean? What is an equilibrium in this framework?

## Nash Equilibrium

1. Suppose you know that strategy $s_i$ is dominated by strategy $s_i'$. Obviously you would chose $s_i'$ every day of the week.
2. Now, to chose some strategy $s_i'$, you might need less than dominance. If you have some clue about what your opponent will do, then you just need to chose your strategy to maximize our payoff given what you expect the other players do, so you do not need to evaluate outcomes in unlikely scenarios.

## Nash Equilibrium

:::{.callout-note}
## Best Response

If given a fixed strategy profile $\bar{s}_{-i}\in \prod_{j\neq i}S_j$ from the other players, $s_i'\in S_i$ is the **best response** of player $i$ if $$\pi_i(s_i',\bar{s}_{-i})\geq \pi_i(s_i,\bar{s}_{-i})$$ for any $s_i\in S_i$.

:::

. . .

Is this enough to have an equilibrium?

## Nash Equilibrium

No! Every single player needs to be *best responding*.

:::{.callout-note}
## Nash Equilibrium

The strategy profile $s^*=(s_1^*,s_2^*,\dots,s_N^*)\in S_1\times S_2 \times \dots \times S_N$ is a **Nash Equilibrium** if

$$\pi_i(s_i^*,s_{-i}^*)\geq \pi_i(s_i,s_{-i}^*),\quad \forall s_i\in S_i,\ \forall i\in \{1,\dots,N\}$$

:::

Every $s_k^*$ is itself a best response to $s_{-k}^*$, and then, nobody has incentives to **unilaterally** change their decision.

## Nash Equilibrium

Let's check the proposed solution we found using IEDS for the game:

| P1 - P2 | Left | Right |
| --: | :--: | :--: |
| Up | <span style="color:red; font-weight:bold;">(1,1)</span>  | (0,1) |
| Middle | (0,2) | (1,0) |
| Down | (0,-1) | (0,0) |

. . .

$(Up,Left)$ is indeed a **Nash Equilibrium**, as every player is *best responding*, or no player can unilaterally profit from deviating from the NE.

## Nash Equilibrium

:::{.callout-important}

## Proposition

If in a game there is an outcome to IEDS. Then this outcome is a Nash Equilibrium. However, a Nash Equilibrium not always can be reached using IEDS.

:::

We just saw an example of a IEDS where it was a NE. Let's check an example where we have a NE that is not IEDS reachable.

## Nash Equilibrium

There is classical game known as the Coordination game. Suppose two friends want to meet to catch up. They decide to go to some concert at 19:30.

| P1-P2 | 19:30 | 17:30 |
| --: | :--: | :--: |
| 19:30 | (1,1) | (0,0) |
| 17:30 | (0,0) | (0,0) |

1. What are the NE of this game?
2. What is the solution using IEDS?

:::{.notes}

Note that *(19:30,19:30)* and *(17:30,17:30)* are both NE of this game, however using IEDS you only reach *(1,1)$

:::

# Bibliography

## Bibliography

These slides took definitions and examples from the book:

Strategies and Games: Theory and Applications from Prajit Dutta. 2001 MIT Press. Chapters 3-5, and 6-10.