---
title: "Fundamentals of <br> Game Theory II"
author: "Paulo Fagandini"
institute: "Prague University of Economics and Business <br> Faculty of Informatics and Statistics"
format: 
  revealjs:
    self-contained: false
    logo: ../images/vse.jpg
    slide-number: true
    cross-ref: true
    incremental: true
    math: 
      method: mathjax
    transition: slide
    footer: "Economics of Incentives"
    from: markdown+emoji
    code-overflow: wrap
    code-block-font-size: 0.75em
    progress: true
editor: source

---
<!-- 
<div style="font-size: 70%;">
</div>
-->

# Backward Induction

## Extensive Representation of a Game

We have a somehow informal definition of the extensive games, let's formalize it. There are **three consistency requirements**:

1. Single starting point
2. No Cycles
3. One way to Proceed

:::{.notes}

1. It is important to know where the game starts, and so there must be one, and only one, starting point. Hence, a situation as two games in parallel is unacceptable.
2. It is important that we not hit an impasse while playing the game; it must not be possible for the branches of a tree ot double back and create a cycle.
3. It is important tha there be no ambiguity about how a game proceeds, and so there must not be two or more branches leading to a node.

:::

## Extensive Representation of a Game

:::{.callout-note}

## Definition

The **predecessors** of a node, say $\alpha$, are those nodes from which you can go (through a sequence of branches) to $\alpha$.

:::

## Extensive Representation of a Game

The three consisntey requirements can be defined using the definition of a predecessor:

<div style="font-size: 70%;">

1. *A node cannot be a predecessor to itself.*
2. *A predecessor's predecessor is also a predecessor:* if a node $\beta$ is a predecessor of $\alpha$, and a node $\gamma$ is, in turn, a predecessor of $\beta$, then $\gamma$ is a predecessor of $\alpha$ as well.
3. *Predecessors can be ranked:* if $\beta$ and $\gamma$ are both predecessors of $\alpha$, it must be the case that either $\beta$ is a predecessor of $\gamma$ or vice-versa.
4. *There must be a common predecessor*: Consider any two nodes, $\alpha$ and $\beta$, neither of which precedes the other. Then there must be a node $\gamma$ that is the predecessor of both $\alpha$ and $\beta$.

</div>

## Extensive Representation of a Game

:::{.callout-tip}

## Definition (Refresh)

A player's **strategy** is a *complete, conditional* plan of action. It is *conditional* in that it tells a player which branch to follow out of a decision node *if* the game arrives at that node. It is *complete* in that it tells him what to choose at every relevant decision node.

:::

:::{.callout-important}

## Definition

A **mixed strategy**, for extensive form games, is defined exactly as it was for strategic form games: a probability distribution over the pure strategies.

:::

## Extensive Representation of a Game

We know at least 2 sources of uncertainty in the game:

1. Simoultaneity (not really uncertainty in the traditional sense, but a player plays not knowing what the other did)
2. Mixed strategies

. . .

There is another possible source of uncertainty:

. . . 

**Nature**

## Extensive Representation of a Game

:::{.callout-note}

## Definition

A **chance node** is a node that represents several random possibilities.

:::

# Subgame Perfect Equilibrium

# Infinitely Repeated Games


# Bibliography

## Bibliography

These slides took definitions and examples from the book:

Strategies and Games: Theory and Applications from Prajit Dutta. 2001 MIT Press. Chapters 11 to 18.