---
title: "Problem Set"
author: "Paulo Fagandini"
date: "Jan 19, 2026"
format:
  pdf:
    documentclass: exam
    include-in-header:
      text: |
        \usepackage{tikz}
        \printanswers  % or \noprintanswers
---

\begin{questions}
\question Consider the following game:

\begin{center}
    \begin{tikzpicture}[scale=1.5,font=\footnotesize]
        \tikzstyle{solid node}=[circle,draw,inner sep=1.5,fill=black]
        \tikzstyle{hollow node}=[circle,draw,inner sep=1.5]
        \tikzstyle{level 1}=[level distance=15mm,sibling distance=3.5cm]
        \tikzstyle{level 2}=[level distance=15mm,sibling distance=1.5cm]
        \tikzstyle{level 3}=[level distance=15mm,sibling distance=1cm]

        \node(0)[solid node,label=above:{$P1$}]{}
            child{node[solid node,label=above left:{$P2$}]{}
            child{node[hollow node,label=below:{$(1,2)$}]{} edge from parent node[left]{$C$}}
            child{node[hollow node,label=below:{$(1,-1)$}]{} edge from parent node[left]{$D$}}
            child{node[hollow node,label=below:{$(0,2)$}]{} edge from parent node[right]{$E$}}
            edge from parent node[left,xshift=-5]{$A$}
            }
            child{node[solid node,label=above right:{$P2$}]{}
            child{node[hollow node,label=below:{$(2,2)$}]{} edge from parent node[left]{$F$}}
            child{node[hollow node,label=below:{$(1,3)$}]{} edge from parent node[right]{$G$}}
            edge from parent node[right,xshift=5]{$B$}
        };
    \end{tikzpicture}
\end{center}

\begin{parts}

    \part[10] List all possible strategies form Players 1 and 2.

    \begin{solution}

        The sets of strategies for players 1 and 2 respectively are $S_1=\{(A), (B)\}$, and $S_2=\{(C,F), (C,G), (D,F), (D,G), (E,F), (E,F)\}$.
    \end{solution}
    
    \part[5] List two strategy profiles for this game.

    \begin{solution}
        It is a set of strategies for each game, $(s_1,s_2)$ with $s_1\in S_1$ and $s_2\in S_2$.
    \end{solution}

    \part[5] Find the Nash Equilibrium in pure strategies of this game.

    \begin{solution}
        The Nash Equilibria are $(A,(C,G))$, $(B,(C,G))$, and $(B,(E,G))$.
    \end{solution}

\end{parts}

\question[15] Suppose two countries can decide to spend more in the \textbf{A}rmy, or more on \textbf{H}ospitals. They would both rather spend little money on arms buildup (and more on hospitals), but realize that if they outspend the other country they will have a tactical superiority, so they could impose geopolitical power on the other country. If they spend the same (large) amount, though, they will be deadlocked - much the same way that they would be deadlocked if they both spent the same, but smaller, amount. Propose payoffs for this situation, assuming symmetric countries (\textit{i.e.} assume they have the same amount of money and population), and model this as a game using the strategic representation. What could be a Nash Equilibrium?

\begin{solution}

    This is a classical prissoner's dilemma. We have the hint that the countries could spend more in the army ($A$), or in hospitals ($H$). You can only enjoy good health if no other country is invading you, and therefore the payoff matrix would look something like this:

    \begin{center}
        \begin{tabular}{r|cc}
            $1 - 2$ & $A$ & $H$ \\
            \hline
            $A$ & (5,5) & (12,-2) \\
            $H$ & (-2,12) & (10,10)
        \end{tabular}
    \end{center}

Suppose the other country spends more in Hospitals. Then you can invest more in the army, overrun theme easily (cheaply) and keep their hospitals for yourself and have security.

If both spend more in the Army. Then both have security (they know they cannot be invaded), however they will have a weak health system (5,5)

If both spend more in the Health system. Both have great healthcare, and given there are no external risks to their security (the other country also decided to spend more in their healthcare system instead of speding in the army), they can enjoy it.

\end{solution}

\question Consider the situation of the Tragedy of the Commons, with the same variables, dynamics and constraints [Chapter 7, Strategies and Games: Theory and Practice, Prajit K. Dutta, MIT Press 2001]. Consider the case where, instead of 2 consumers, there are $N\in\mathbb{N}$ consumers.

\begin{parts}

    \part[5] Find the best response for consumer $1$. [Hint: Note you can use symmetry \textbf{after} doing the derivatives.]
    \begin{solution}
        The optimization problem for consumer 1 is:

        \begin{align*}
            \max_{c_1} \ln \left(c_1\right) + \ln \left(\frac{y-c_1-\sum_{j>1}c_j}{N}\right)
        \end{align*}

        Taking derivatives and equalizing to zero we get:

        \begin{align*}
            \frac{1}{c_1} - \frac{1}{y-c_1-\sum_{j>1}c_j}=0\\
            c_1 = y-c_1-\sum_{j>1}c_j\\
            c_1 = \frac{y-\sum_{j>1}c_j}{2}
        \end{align*}

        Now, by symmetry, we have $c_1=c_i$ $\forall i=1,\dots,N$.

        \begin{align*}
            c_1 = \frac{y-\sum_{j>1}c_1}{2}\\
            (N+1) c_1 = y \\
            c_1 = \frac{y}{N+1}
        \end{align*}

    \end{solution}

    \part[5] Find the Nash Equilibrium, and show that as $N\rightarrow\infty$ then $y^1\rightarrow 0$.[Remember that $y^1$ is what is left for the "future"]
    \begin{solution}
        Directly from the previous question, we have 
        
        $$c_1 = \frac{y}{N+1}\quad \Rightarrow \quad y^1= y-\frac{N}{N+1}y=\frac{y}{N+1}$$
        
        $$\frac{y}{N+1}\underset{N\rightarrow\infty}{\rightarrow}0$$
    \end{solution}

    \part[5] Find the total utility under this Nash Equilibrium. [Hint: Remember to use symmetry]
    \begin{solution}
        $c_i = \frac{y}{N+1}$ and $c_i^1=\frac{y}{N(N+1)}$, and then total utility is:

        \begin{align*}
            TU_{NE} = N \ln \left(\frac{y}{N+1}\right)+N \ln \left(\frac{y}{N(N+1)}\right) = N \ln \left(\frac{y^2}{N(N+1)^2}\right)
        \end{align*}
    \end{solution}

    \part[5] Find the Socially Optimal consumption for each consumer.
    \begin{solution}
        \begin{align*}
            \max_{c_i} \ln (c_i) + \sum_{j\neq i} \ln (c_j) + N \ln \left(\frac{y-c_i - \sum_{j\neq i}c_j}{N}\right)
        \end{align*}

        From the First Order Condition we obtain:

        \begin{align*}
            \frac{1}{c_i}-\frac{N}{\left(y-c_i-\sum_{j\neq i}c_j\right)}=0
        \end{align*}
        Now using symmetry, $c_i=c_j$ $\forall j=1,\dots,N$:
        \begin{align*}
            y-Nc_i=Nc_i\\
            c_i = \frac{y}{2N}
        \end{align*}

        In the future we already know that we will be able to consume an equal share of what is left:

        \begin{align*}
            c_i^1=\frac{y-N\frac{y}{2N}}{N}=\frac{y}{2N}
        \end{align*}

        Which was expected from the exercise for 2 consumers.

    \end{solution}

    \part[5] Find the total utility under the Social Optimum:
    \begin{solution}

        Total utility is:
        \begin{align*}
            TU_{SO} = N \ln \left(\frac{y}{2N}\right) + N \ln \left(\frac{y}{2N}\right) = N\ln \left(\frac{y^2}{4N^2}\right)
        \end{align*}

    \end{solution}

    \part[5] Show that total utility under the Nash Equilibrium diverges from the total utility under the socially optimum as $N\rightarrow\infty$.
    \begin{solution}
        \begin{align*}
            TU_{SO}-TU_{NE}&= N\ln \left(\frac{y^2}{4N^2}\right)-N \ln \left(\frac{y^2}{N(N+1)^2}\right)\\
                        &= N \left(\ln \left(\frac{y^2}{4N^2}\right)-\ln \left(\frac{y^2}{N(N+1)^2}\right)\right)\\
                        &= N \ln \left(\frac{(N+1)^2}{4N}\right)\underset{N\rightarrow\infty}{\rightarrow}\infty
        \end{align*}
    \end{solution}

\end{parts}

\end{questions}