---
title: "Exercises Set"
author: "Paulo Fagandini"
date: "Jan 19, 2026"
format:
  pdf:
    documentclass: exam
    geometry: a4paper
    include-in-header:
      text: |
        \usepackage{tikz}
        \printanswers  % or \noprintanswers
---

\begin{questions}
\question Suppose, to begin with, there are two matches in one pile and a single match in the other pile. Let us write this configuration as $(2,1)$. Winning is preferred to losing and, hence, the payoff number associated with winning must be higher than the one that corresponds to losing; suppose that these numbers are, respectively, $1$, and $-1$.

\begin{parts}

    \part What is the strategic representation of this game?

    \begin{solution}
        \begin{center}
            \begin{tabular}{r|cccc}
            1 - 2 & $(l,l)$ & $(l,r)$ & $(r,l)$ & $(r,r)$ \\
            \hline
            $u$ & $(1,-1)$ & $(1,-1)$ & $(1,-1)$ & $(1,-1)$ \\
            $m$ & $(-1,1)$ & $(-1,1)$ & $(-1,1)$ & $(-1,1)$ \\
            $d$ & $(1,-1)$ & $(-1,1)$ & $(1,-1)$ & $(-1,1)$
            \end{tabular}
        \end{center}
    \end{solution}

    \part What is the extensive representation of this game?

    \begin{solution}

    \end{solution}

\end{parts}

\begin{center}
    \begin{tikzpicture}[scale=1.5,font=\footnotesize]
        \tikzstyle{solid node}=[circle,draw,inner sep=1.5,fill=black]
        \tikzstyle{hollow node}=[circle,draw,inner sep=1.5]
        \tikzstyle{level 1}=[level distance=15mm,sibling distance=3.5cm]
        \tikzstyle{level 2}=[level distance=15mm,sibling distance=1.5cm]
        \tikzstyle{level 3}=[level distance=15mm,sibling distance=1cm]

        \node(0)[solid node,label=above:{$P1$}]{}
            child{node[solid node,label=above left:{$P2$}]{}
            child{node[hollow node,label=below:{$(1,2)$}]{} edge from parent node[left]{$C$}}
            child{node[hollow node,label=below:{$(1,-1)$}]{} edge from parent node[left]{$D$}}
            child{node[hollow node,label=below:{$(0,2)$}]{} edge from parent node[right]{$E$}}
            edge from parent node[left,xshift=-5]{$A$}
            }
            child{node[solid node,label=above right:{$P2$}]{}
            child{node[hollow node,label=below:{$(2,2)$}]{} edge from parent node[left]{$F$}}
            child{node[hollow node,label=below:{$(1,3)$}]{} edge from parent node[right]{$G$}}
            edge from parent node[right,xshift=5]{$B$}
        };
    \end{tikzpicture}
\end{center}

\begin{parts}

    \part[10] List all possible strategies form Players 1 and 2.

    \begin{solution}

        The sets of strategies for players 1 and 2 respectively are $S_1=\{(A), (B)\}$, and $S_2=\{(C,F), (C,G), (D,F), (D,G), (E,F), (E,F)\}$.
    \end{solution}
    
    \part[5] List two strategy profiles for this game.

    \begin{solution}
        It is a set of strategies for each game, $(s_1,s_2)$ with $s_1\in S_1$ and $s_2\in S_2$.
    \end{solution}

    \part[5] Find the Nash Equilibrium in pure strategies of this game.

    \begin{solution}
        The Nash Equilibria are $(A,(C,G))$, $(B,(C,G))$, and $(B,(E,G))$.
    \end{solution}

\end{parts}

\question[15] Consider the following game tree:
% your tikz code here
\end{questions}